language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '11'
  - '10'
  - '8'
  - '6'
jobs:
  include:
    - stage: npm release
      node_js: "10"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        on: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
